### PR TITLE
Misc fixes before release candidate

### LINKED ISSUE #7: Changes before Release Candidate
*Changes*

- [x] Update name/scheduling of the sync rule when user updates in DHIS2
- [x] Add a trace with link to instance #/notifications/id
- [x] Add trace when server starts (boot-up welcome)

*Documentation*

- [x] Add more details about log
- [x] Add details about how the script works

### PR DESCRIPTION
**Pull request by SferaDev**
### :pushpin: References

* **Issue:** Closes #7

### CODE REVIEW

**Comment by adrianq** [comment]
@SferaDev I am getting the following error here:
image

Am I doing something wrong here? I am getting this error in our dev server in case you want to have a look at it btw.

**Comment by SferaDev** [comment]
> @SferaDev I am getting the following error here:
> image
> 
> Am I doing something wrong here? I am getting this error in our dev server in case you want to have a look at it btw.

I changed to fileSync because the log file was not updated until a long time. But since I also added the logs to stdout it can be reverted back to file now.

**Comment by adrianq** [comment]
@SferaDev This is working like a charm now! Just one final thing before merging it. Can you have a look at this https://github.com/EyeSeeTea/metadata-synchronization-server/pull/6#discussion_r323628964 ?

**Comment by SferaDev** [comment]
> @SferaDev This is working like a charm now! Just one final thing before merging it. Can you have a look at this [#6 (comment)](https://github.com/EyeSeeTea/metadata-synchronization-server/pull/6#discussion_r323628964) ?

```
sfera@coruscant /m/d/W/E/metadata-synchronization-server> node metadata-synchronization-server.js --help
Options:
  --help        Show help                                              [boolean]
  --version     Show version number                                    [boolean]
  --config, -c  Configuration file                            [string] [default:
         "/mnt/d/Workspace/EST/metadata-synchronization-server/app-config.json"]
```

**Comment by adrianq** [comment]
mmm I was thinking more about automatically look for a 'app-config.json' file in the folder if no parameter is passed...

**Comment by SferaDev** [comment]
> mmm I was thinking more about automatically look for a 'app-config.json' file in the folder if no parameter is passed...

This is what it is doing, let me upload the change so you can test it. The default value for the configuration file in `` --help`` changes depending on the folder you are on.

**Pull request merged**
